**Mini Project Data Exploration**

In [132]:
pip install requests

Collecting requests
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Using cached charset_normalizer-3.4.4-cp313-cp313-macosx_10_13_universal2.whl.metadata (37 kB)
Collecting idna<4,>=2.5 (from requests)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.21.1 (from requests)
  Using cached urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2017.4.17 (from requests)
  Using cached certifi-2026.1.4-py3-none-any.whl.metadata (2.5 kB)
Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.4-cp313-cp313-macosx_10_13_universal2.whl (208 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Using cached urllib3-2.6.3-py3-none-any.whl (131 kB)
Using cached certifi-2026.1.4-py3-none-any.whl (152 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [requests]
Successfully installed certifi-2026.1.4 charset_normalizer-3.4.4 idna-3.11 requests-2.32.5 urllib3-2.6.3
Note: you may need to restart the kernel to use updated packages.

In [95]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import unicodedata

In [96]:
df = pd.read_csv("/Users/rebeccayedid/Desktop/SI CLASSES/SI 699/mini project/US-National-Parks_Use_1979-2023_By-Month.csv")

df.head()

,ParkName,UnitCode,ParkType,Region,State,Year,Month,RecreationVisits,NonRecreationVisits,TentCampers,RVCampers,Backcountry
0,Acadia NP,ACAD,National Park,Northeast,ME,1979,1,6011,15252,102,13,0
1,Acadia NP,ACAD,National Park,Northeast,ME,1979,2,5243,13776,53,8,0
2,Acadia NP,ACAD,National Park,Northeast,ME,1979,3,11165,15252,176,37,0
3,Acadia NP,ACAD,National Park,Northeast,ME,1979,4,219351,37657,1037,459,0
4,Acadia NP,ACAD,National Park,Northeast,ME,1979,5,339416,50616,3193,1148,0

In [19]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 33395 entries, 0 to 33394
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ParkName             33395 non-null  str
 1   UnitCode             33395 non-null  str
 2   ParkType             33395 non-null  str
 3   Region               33395 non-null  str
 4   State                33395 non-null  str
 5   Year                 33395 non-null  int64
 6   Month                33395 non-null  int64
 7   RecreationVisits     33395 non-null  int64
 8   NonRecreationVisits  33395 non-null  int64
 9   TentCampers          33395 non-null  int64
 10  RVCampers            33395 non-null  int64
 11  Backcountry          33395 non-null  int64
dtypes: int64(7), str(5)
memory usage: 3.1 MB

,Year,Month,RecreationVisits,NonRecreationVisits,TentCampers,RVCampers,Backcountry
count,33395.00000,33395.000000,3.339500e+04,3.339500e+04,33395.000000,33395.000000,33395.000000
mean,2001.28124,6.499835,9.612765e+04,3.018823e+04,3548.919449,2505.262824,1585.983650
std,12.90109,3.452025,1.663928e+05,1.155649e+05,10436.616589,7368.140926,4671.575495
min,1979.00000,1.000000,0.000000e+00,-3.296400e+04,0.000000,0.000000,0.000000
25%,1990.00000,3.500000,9.998000e+03,0.000000e+00,0.000000,0.000000,0.000000
50%,2001.00000,6.000000,4.084900e+04,5.090000e+02,154.000000,26.000000,77.000000
75%,2012.00000,9.000000,1.052935e+05,8.339000e+03,1980.000000,1404.000000,569.000000
max,2023.00000,12.000000,1.761918e+06,1.646888e+06,179369.000000,134586.000000,62848.000000

In [97]:
loc_df = pd.read_csv("/Users/rebeccayedid/Desktop/SI CLASSES/SI 699/mini project/df_2.csv")

loc_df.head()

,Unnamed: 0,Name,Image,Location,Date established as park[7][12],Area (2021)[13],Recreation visitors (2021)[11],Description
0,0,Acadia,NaN,"Maine.mw-parser-output .geo-default,.mw-parser...","February 26, 1919","49,071.40 acres (198.6 km2)",4069098,Covering most of Mount Desert Island and other...
1,1,American Samoa,NaN,American Samoa14°15′S 170°41′W﻿ / ﻿14.25°S 170...,"October 31, 1988","8,256.67 acres (33.4 km2)",8495,The southernmost national park is on three Sam...
2,2,Arches,NaN,Utah38°41′N 109°34′W﻿ / ﻿38.68°N 109.57°W,"November 12, 1971","76,678.98 acres (310.3 km2)",1806865,"This site features more than 2,000 natural san..."
3,3,Badlands,NaN,South Dakota43°45′N 102°30′W﻿ / ﻿43.75°N 102.50°W,"November 10, 1978","242,755.94 acres (982.4 km2)",1224226,"The Badlands are a collection of buttes, pinna..."
4,4,Big Bend,NaN,Texas29°15′N 103°15′W﻿ / ﻿29.25°N 103.25°W,"June 12, 1944","801,163.21 acres (3,242.2 km2)",581220,Named for the prominent bend in the Rio Grande...

In [32]:
df['ParkName'].unique()

<StringArray>
[                      'Acadia NP',                       'Arches NP',
                     'Badlands NP',                     'Big Bend NP',
                     'Biscayne NP', 'Black Canyon of the Gunnison NP',
                 'Bryce Canyon NP',                  'Canyonlands NP',
                 'Capitol Reef NP',             'Carlsbad Caverns NP',
              'Channel Islands NP',                     'Congaree NP',
                  'Crater Lake NP',              'Cuyahoga Valley NP',
                 'Death Valley NP',                'Denali NP & PRES',
                 'Dry Tortugas NP',                   'Everglades NP',
   'Gates of the Arctic NP & PRES',                 'Gateway Arch NP',
           'Glacier Bay NP & PRES',                      'Glacier NP',
                 'Grand Canyon NP',                  'Grand Teton NP',
                  'Great Basin NP',      'Great Sand Dunes NP & PRES',
        'Great Smoky Mountains NP',          'Guadalupe Mountains NP',
                    'Haleakala NP',             'Hawaii Volcanoes NP',
                  'Hot Springs NP',                'Indiana Dunes NP',
                  'Isle Royale NP',                  'Joshua Tree NP',
                'Katmai NP & PRES',                 'Kenai Fjords NP',
                 'Kings Canyon NP',                 'Kobuk Valley NP',
            'Lake Clark NP & PRES',              'Lassen Volcanic NP',
                 'Mammoth Cave NP',                   'Mesa Verde NP',
                'Mount Rainier NP', 'National Park of American Samoa',
       'New River Gorge NP & PRES',               'North Cascades NP',
                      'Olympic NP',             'Petrified Forest NP',
                    'Pinnacles NP',                      'Redwood NP',
               'Rocky Mountain NP',                      'Saguaro NP',
                      'Sequoia NP',                   'Shenandoah NP',
           'Theodore Roosevelt NP',               'Virgin Islands NP',
                    'Voyageurs NP',                  'White Sands NP',
                    'Wind Cave NP',    'Wrangell-St. Elias NP & PRES',
                  'Yellowstone NP',                     'Yosemite NP',
                         'Zion NP']
Length: 63, dtype: str

In [35]:
loc_df['Name'].unique()

<StringArray>
[                      'Acadia',               'American Samoa',
                       'Arches',                     'Badlands',
                     'Big Bend',                     'Biscayne',
 'Black Canyon of the Gunnison',                 'Bryce Canyon',
                  'Canyonlands',                 'Capitol Reef',
           'Carlsbad Caverns *',              'Channel Islands',
                     'Congaree',                  'Crater Lake',
              'Cuyahoga Valley',                 'Death Valley',
                       'Denali',                 'Dry Tortugas',
                   'Everglades',          'Gates of the Arctic',
                 'Gateway Arch',                      'Glacier',
                  'Glacier Bay',               'Grand Canyon *',
                  'Grand Teton',                  'Great Basin',
             'Great Sand Dunes',        'Great Smoky Mountains',
          'Guadalupe Mountains',                    'Haleakalā',
            'Hawaiʻi Volcanoes',                  'Hot Springs',
                'Indiana Dunes',                  'Isle Royale',
                  'Joshua Tree',                       'Katmai',
                 'Kenai Fjords',                 'Kings Canyon',
                 'Kobuk Valley',                   'Lake Clark',
              'Lassen Volcanic',                 'Mammoth Cave',
                 'Mesa Verde *',                'Mount Rainier',
              'New River Gorge',               'North Cascades',
                      'Olympic',             'Petrified Forest',
                    'Pinnacles',                    'Redwood *',
               'Rocky Mountain',                      'Saguaro',
                      'Sequoia',                   'Shenandoah',
           'Theodore Roosevelt',               'Virgin Islands',
                    'Voyageurs',                  'White Sands',
                    'Wind Cave',         'Wrangell–St. Elias *',
                  'Yellowstone',                   'Yosemite *',
                         'Zion']
Length: 63, dtype: str

In [98]:
def clean_park_name(name):
    # normalize unicode characters (fixes Haleakalā, Hawaiʻi, etc.)
    name = unicodedata.normalize('NFKD', name)
    name = name.encode('ascii', 'ignore').decode('utf-8')

    name = name.lower()
    
    # normalize punctuation
    name = name.replace('*', '')
    name = name.replace('–', '-')
    name = name.replace('.', '')
    
    # remove park designations
    name = re.sub(r'national park of', '', name)
    name = re.sub(r'national park', '', name)
    name = re.sub(r'np.*pres', '', name)
    name = re.sub(r'np', '', name)
    name = re.sub(r'preserve', '', name)
    
    # replace hyphens with spaces
    name = name.replace('-', ' ')
    
    # clean up whitespace
    name = re.sub(r'\s+', ' ', name).strip()
    
    return name

In [99]:
df['clean_name'] = df['ParkName'].apply(clean_park_name)
loc_df['clean_name'] = loc_df['Name'].apply(clean_park_name)
df.loc[df['ParkName'].str.contains('Wrangell', na=False), 'clean_name'] = 'wrangell st elias'
loc_df.loc[loc_df['Name'].str.contains('Wrangell', na=False), 'clean_name'] = 'wrangell st elias'

In [100]:
unmatched = df[~df['clean_name'].isin(loc_df['clean_name'])]
unmatched[['ParkName', 'clean_name']]

Empty DataFrame
Columns: [ParkName, clean_name]
Index: []

In [101]:
loc_df.head()
loc_df = loc_df[['Name','Location','clean_name']]

In [102]:
loc_df['Location']

0     Maine.mw-parser-output .geo-default,.mw-parser...
1     American Samoa14°15′S 170°41′W﻿ / ﻿14.25°S 170...
2             Utah38°41′N 109°34′W﻿ / ﻿38.68°N 109.57°W
3     South Dakota43°45′N 102°30′W﻿ / ﻿43.75°N 102.50°W
4            Texas29°15′N 103°15′W﻿ / ﻿29.25°N 103.25°W
                            ...
58    South Dakota43°34′N 103°29′W﻿ / ﻿43.57°N 103.48°W
59          Alaska61°00′N 142°00′W﻿ / ﻿61.00°N 142.00°W
60    Wyoming, Montana, Idaho44°36′N 110°30′W﻿ / ﻿44...
61      California37°50′N 119°30′W﻿ / ﻿37.83°N 119.50°W
62            Utah37°18′N 113°03′W﻿ / ﻿37.30°N 113.05°W
Name: Location, Length: 63, dtype: str

In [103]:
import pandas as pd
import re

def extract_decimal_coords(coord_str):
    """Extract decimal latitude and longitude from a string like:
    'Utah38°41′N 109°34′W﻿ / ﻿38.68°N 109.57°W'
    Returns (lat, lon) as floats.
    """
    if pd.isna(coord_str):
        return pd.Series([None, None])
    
    # Remove invisible characters like zero-width space
    coord_str = re.sub(r'[\u200B\uFEFF]', '', coord_str)
    
    # Regex to find the decimal portion after the slash
    match = re.search(r'/\s*([\d\.]+)°([NS])\s*([\d\.]+)°([EW])', coord_str)
    if match:
        lat = float(match.group(1))
        lon = float(match.group(3))
        
        # Adjust for hemisphere
        if match.group(2) == 'S':
            lat = -lat
        if match.group(4) == 'W':
            lon = -lon
        
        return pd.Series([lat, lon])
    
    return pd.Series([None, None])

# Example usage:
loc_df[['Latitude', 'Longitude']] = loc_df['Location'].apply(extract_decimal_coords)

In [104]:
loc_df.head()

,Name,Location,clean_name,Latitude,Longitude
0,Acadia,"Maine.mw-parser-output .geo-default,.mw-parser...",acadia,44.35,-68.21
1,American Samoa,American Samoa14°15′S 170°41′W﻿ / ﻿14.25°S 170...,american samoa,-14.25,-170.68
2,Arches,Utah38°41′N 109°34′W﻿ / ﻿38.68°N 109.57°W,arches,38.68,-109.57
3,Badlands,South Dakota43°45′N 102°30′W﻿ / ﻿43.75°N 102.50°W,badlands,43.75,-102.50
4,Big Bend,Texas29°15′N 103°15′W﻿ / ﻿29.25°N 103.25°W,big bend,29.25,-103.25

In [105]:
new_df = df.merge(
    loc_df,
    on='clean_name',
    how='left',
)

In [106]:
new_df

,ParkName,UnitCode,ParkType,Region,State,Year,Month,RecreationVisits,NonRecreationVisits,TentCampers,RVCampers,Backcountry,clean_name,Name,Location,Latitude,Longitude
0,Acadia NP,ACAD,National Park,Northeast,ME,1979,1,6011,15252,102,13,0,acadia,Acadia,"Maine.mw-parser-output .geo-default,.mw-parser...",44.35,-68.21
1,Acadia NP,ACAD,National Park,Northeast,ME,1979,2,5243,13776,53,8,0,acadia,Acadia,"Maine.mw-parser-output .geo-default,.mw-parser...",44.35,-68.21
2,Acadia NP,ACAD,National Park,Northeast,ME,1979,3,11165,15252,176,37,0,acadia,Acadia,"Maine.mw-parser-output .geo-default,.mw-parser...",44.35,-68.21
3,Acadia NP,ACAD,National Park,Northeast,ME,1979,4,219351,37657,1037,459,0,acadia,Acadia,"Maine.mw-parser-output .geo-default,.mw-parser...",44.35,-68.21
4,Acadia NP,ACAD,National Park,Northeast,ME,1979,5,339416,50616,3193,1148,0,acadia,Acadia,"Maine.mw-parser-output .geo-default,.mw-parser...",44.35,-68.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33390,Zion NP,ZION,National Park,Intermountain,UT,2023,8,458449,1860,13565,9225,525,zion,Zion,Utah37°18′N 113°03′W﻿ / ﻿37.30°N 113.05°W,37.30,-113.05
33391,Zion NP,ZION,National Park,Intermountain,UT,2023,9,491799,1800,9870,8306,1172,zion,Zion,Utah37°18′N 113°03′W﻿ / ﻿37.30°N 113.05°W,37.30,-113.05
33392,Zion NP,ZION,National Park,Intermountain,UT,2023,10,504584,1860,9625,9191,1241,zion,Zion,Utah37°18′N 113°03′W﻿ / ﻿37.30°N 113.05°W,37.30,-113.05
33393,Zion NP,ZION,National Park,Intermountain,UT,2023,11,284978,1800,6205,7035,589,zion,Zion,Utah37°18′N 113°03′W﻿ / ﻿37.30°N 113.05°W,37.30,-113.05
33394,Zion NP,ZION,National Park,Intermountain,UT,2023,12,212443,1860,3329,4389,177,zion,Zion,Utah37°18′N 113°03′W﻿ / ﻿37.30°N 113.05°W,37.30,-113.05

In [112]:

new_df = new_df.drop(columns=['Name'])

In [115]:
new_df = new_df.drop(columns=['Location'])

In [116]:
new_df

,ParkName,UnitCode,ParkType,Region,State,Year,Month,RecreationVisits,NonRecreationVisits,TentCampers,RVCampers,Backcountry,clean_name,Latitude,Longitude
0,Acadia NP,ACAD,National Park,Northeast,ME,1979,1,6011,15252,102,13,0,acadia,44.35,-68.21
1,Acadia NP,ACAD,National Park,Northeast,ME,1979,2,5243,13776,53,8,0,acadia,44.35,-68.21
2,Acadia NP,ACAD,National Park,Northeast,ME,1979,3,11165,15252,176,37,0,acadia,44.35,-68.21
3,Acadia NP,ACAD,National Park,Northeast,ME,1979,4,219351,37657,1037,459,0,acadia,44.35,-68.21
4,Acadia NP,ACAD,National Park,Northeast,ME,1979,5,339416,50616,3193,1148,0,acadia,44.35,-68.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33390,Zion NP,ZION,National Park,Intermountain,UT,2023,8,458449,1860,13565,9225,525,zion,37.30,-113.05
33391,Zion NP,ZION,National Park,Intermountain,UT,2023,9,491799,1800,9870,8306,1172,zion,37.30,-113.05
33392,Zion NP,ZION,National Park,Intermountain,UT,2023,10,504584,1860,9625,9191,1241,zion,37.30,-113.05
33393,Zion NP,ZION,National Park,Intermountain,UT,2023,11,284978,1800,6205,7035,589,zion,37.30,-113.05
33394,Zion NP,ZION,National Park,Intermountain,UT,2023,12,212443,1860,3329,4389,177,zion,37.30,-113.05

**Here is where we are changing our data to be total visits by park**

In [117]:
pip install pyvalhalla

Collecting pyvalhalla
  Downloading pyvalhalla-3.6.2-cp312-abi3-macosx_14_0_arm64.whl.metadata (14 kB)
Downloading pyvalhalla-3.6.2-cp312-abi3-macosx_14_0_arm64.whl (23.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.0/23.0 MB 6.9 MB/s  0:00:03m0:00:0100:01
Installing collected packages: pyvalhalla
Successfully installed pyvalhalla-3.6.2
Note: you may need to restart the kernel to use updated packages.

In [119]:
new_df['Region'].unique()

<StringArray>
[    'Northeast ', 'Intermountain ',       'Midwest ',     'Southeast ',
  'Pacific West ',         'Alaska']
Length: 6, dtype: str

In [125]:
keep_cols = ['ParkName', 'clean_name', 'Region', 'Latitude', 'Longitude']
total_visitation = (
    new_df.groupby(keep_cols, as_index=False)['RecreationVisits']
    .sum()
)
total_visitation

,ParkName,clean_name,Region,Latitude,Longitude,RecreationVisits
0,Acadia NP,acadia,Northeast,44.35,-68.21,134113188
1,Arches NP,arches,Intermountain,38.68,-109.57,39675085
2,Badlands NP,badlands,Midwest,43.75,-102.50,45958032
3,Big Bend NP,big bend,Intermountain,29.25,-103.25,14476096
4,Biscayne NP,biscayne,Southeast,25.65,-80.08,20815641
...,...,...,...,...,...,...
58,Wind Cave NP,wind cave,Midwest,43.57,-103.48,27639533
59,Wrangell-St. Elias NP & PRES,wrangell st elias,Alaska,61.00,-142.00,2039977
60,Yellowstone NP,yellowstone,Intermountain,44.60,-110.50,139394679
61,Yosemite NP,yosemite,Pacific West,37.83,-119.50,155709017
62,Zion NP,zion,Intermountain,37.30,-113.05,119116876

In [126]:
total_visitation

,ParkName,clean_name,Region,Latitude,Longitude,RecreationVisits
0,Acadia NP,acadia,Northeast,44.35,-68.21,134113188
1,Arches NP,arches,Intermountain,38.68,-109.57,39675085
2,Badlands NP,badlands,Midwest,43.75,-102.50,45958032
3,Big Bend NP,big bend,Intermountain,29.25,-103.25,14476096
4,Biscayne NP,biscayne,Southeast,25.65,-80.08,20815641
...,...,...,...,...,...,...
58,Wind Cave NP,wind cave,Midwest,43.57,-103.48,27639533
59,Wrangell-St. Elias NP & PRES,wrangell st elias,Alaska,61.00,-142.00,2039977
60,Yellowstone NP,yellowstone,Intermountain,44.60,-110.50,139394679
61,Yosemite NP,yosemite,Pacific West,37.83,-119.50,155709017
62,Zion NP,zion,Intermountain,37.30,-113.05,119116876

In [127]:
regions = total_visitation['Region'].unique()

In [128]:
total_visitation['Region'] = total_visitation['Region'].str.strip()

In [129]:
parks_by_region = {region: df_region for region, df_region in total_visitation.groupby('Region')}

In [133]:
import requests
import json

# Prepare your request
url = "http://localhost:8002/table"

matrix_request = {
    "locations": [
        {"lat": 37.83, "lon": -119.50},  # Yosemite
        {"lat": 44.60, "lon": -110.50}   # Yellowstone
    ],
    "costing": "auto",
    "directions_options": {"units": "miles"}
}

response = requests.post(url, json=matrix_request)
matrix = response.json()

print(matrix['distances'])

ConnectionError: HTTPConnectionPool(host='localhost', port=8002): Max retries exceeded with url: /table (Caused by NewConnectionError("HTTPConnection(host='localhost', port=8002): Failed to establish a new connection: [Errno 61] Connection refused"))

**Haversine as the crow flies distance by region**

In [136]:
import pandas as pd
import numpy as np

# Haversine function
def haversine(lat1, lon1, lat2, lon2):
    R = 3958.8  # Earth radius in miles
    phi1, phi2 = np.radians(lat1), np.radians(lat2)
    dphi = np.radians(lat2 - lat1)
    dlambda = np.radians(lon2 - lon1)
    a = np.sin(dphi/2)**2 + np.cos(phi1)*np.cos(phi2)*np.sin(dlambda/2)**2
    return 2 * R * np.arcsin(np.sqrt(a))

# Load your total visitation dataset
parks = total_visitation

# Clean region column
parks['Region'] = parks['Region'].str.strip()

# Prepare results list
rows = []

# Loop through regions
for region, df_region in parks.groupby('Region'):
    df_region = df_region.reset_index(drop=True)
    for i, row1 in df_region.iterrows():
        for j, row2 in df_region.iterrows():
            dist = haversine(row1["Latitude"], row1["Longitude"], row2["Latitude"], row2["Longitude"])
            rows.append({
                "region": region,
                "from_park": row1["ParkName"],
                "to_park": row2["ParkName"],
                "distance_miles": dist
            })

# Convert to DataFrame
distances_df = pd.DataFrame(rows)

In [137]:
distances_df

,region,from_park,to_park,distance_miles
0,Alaska,Denali NP & PRES,Denali NP & PRES,0.000000
1,Alaska,Denali NP & PRES,Gates of the Arctic NP & PRES,317.640328
2,Alaska,Denali NP & PRES,Glacier Bay NP & PRES,561.196044
3,Alaska,Denali NP & PRES,Katmai NP & PRES,366.145067
4,Alaska,Denali NP & PRES,Kenai Fjords NP,237.252793
...,...,...,...,...
848,Southeast,Virgin Islands NP,Dry Tortugas NP,1243.471531
849,Southeast,Virgin Islands NP,Everglades NP,1144.547108
850,Southeast,Virgin Islands NP,Great Smoky Mountains NP,1660.027026
851,Southeast,Virgin Islands NP,Mammoth Cave NP,1836.007240
852,Southeast,Virgin Islands NP,Virgin Islands NP,0.000000